insert into DOGGOS (ID, DOGGO_NAME) OVERRIDING SYSTEM VALUE VALUES (1, 'Sol');
insert into DOGGOS (ID, DOGGO_NAME) OVERRIDING SYSTEM VALUE VALUES (2, 'Boris');
insert into DOGGOS (ID, DOGGO_NAME) OVERRIDING SYSTEM VALUE VALUES (3, 'Milo');
insert into DOGGOS (ID, DOGGO_NAME) OVERRIDING SYSTEM VALUE VALUES (4, 'AJ');